/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AutoMoverPlugin
});
module.exports = __toCommonJS(main_exports);

// Utils/LoggerUtil.ts
var import_obsidian = require("obsidian");
var _LoggerUtil = class {
  constructor() {
    this.plugin = null;
  }
  /**
   * Returns the singleton instance of LoggerUtil, creating it on first access.
   *
   * @returns LoggerUtil
   */
  static getInstance() {
    if (!_LoggerUtil.instance) {
      _LoggerUtil.instance = new _LoggerUtil();
    }
    return _LoggerUtil.instance;
  }
  /**
   * Wires the logger to the plugin so it can read the current debug toggle
   * from settings on every call (settings may be reassigned on reload).
   */
  init(plugin) {
    this.plugin = plugin;
  }
  /**
   * Reads the current debug toggle from plugin settings.
   *
   * @returns true if debug logging is enabled, false otherwise
   */
  isDebugEnabled() {
    var _a, _b;
    return ((_b = (_a = this.plugin) == null ? void 0 : _a.settings) == null ? void 0 : _b.debugLogging) === true;
  }
  /**
   * Logs a debug message to the console, prefixed with the plugin tag.
   * No-op when debug logging is disabled in settings.
   *
   * @param args - Values to log
   * @returns void
   */
  debug(...args) {
    if (!this.isDebugEnabled())
      return;
    console.debug(_LoggerUtil.PREFIX, ...args);
  }
  /**
   * Logs an informational message to the console, prefixed with the plugin tag.
   *
   * @param args - Values to log
   * @returns void
   */
  info(...args) {
    console.info(_LoggerUtil.PREFIX, ...args);
  }
  /**
   * Logs a warning message to the console, prefixed with the plugin tag.
   *
   * @param args - Values to log
   * @returns void
   */
  warn(...args) {
    console.warn(_LoggerUtil.PREFIX, ...args);
  }
  /**
   * Logs an error message to the console, prefixed with the plugin tag.
   *
   * @param args - Values to log
   * @returns void
   */
  error(...args) {
    console.error(_LoggerUtil.PREFIX, ...args);
  }
  /**
   * Console.info + Obsidian Notice. `message` shows in both places; any
   * additional args (e.g. an Error or rule object) are appended to the
   * console line only.
   */
  infoNotice(message, ...extra) {
    console.info(_LoggerUtil.PREFIX, message, ...extra);
    new import_obsidian.Notice(message, _LoggerUtil.NOTICE_DURATION_MS);
  }
  /**
   * Console.warn + Obsidian Notice. `message` shows in both places; any
   * additional args are appended to the console line only.
   *
   * @param message - The user-facing warning message
   * @param extra - Optional values appended to the console line only
   * @returns void
   */
  warnNotice(message, ...extra) {
    console.warn(_LoggerUtil.PREFIX, message, ...extra);
    new import_obsidian.Notice(message, _LoggerUtil.NOTICE_DURATION_MS);
  }
  /**
   * Console.error + Obsidian Notice. `message` shows in both places; any
   * additional args (e.g. an Error or rule object) are appended to the
   * console line only.
   *
   * @param message - The user-facing error message
   * @param extra - Optional values appended to the console line only
   * @returns void
   */
  errorNotice(message, ...extra) {
    console.error(_LoggerUtil.PREFIX, message, ...extra);
    new import_obsidian.Notice(message, _LoggerUtil.NOTICE_DURATION_MS);
  }
};
var LoggerUtil = _LoggerUtil;
LoggerUtil.PREFIX = "[AutoMover]";
LoggerUtil.NOTICE_DURATION_MS = 5e3;
var loggerUtil = LoggerUtil.getInstance();
var LoggerUtil_default = loggerUtil;

// IO/SettingsIO.ts
var import_obsidian2 = require("obsidian");
var SettingsIO = class {
  constructor() {
  }
  /**
   * Returns the singleton instance of SettingsIO, creating it on first access.
   *
   * @returns SettingsIO
   */
  static getInstance() {
    if (!SettingsIO.instance) {
      SettingsIO.instance = new SettingsIO();
    }
    return SettingsIO.instance;
  }
  /**
   * Stores the Obsidian app reference used for vault and dialog access.
   *
   * @param app - The Obsidian App instance
   * @returns void
   */
  init(app) {
    this.app = app;
  }
  /**
   * Exports the plugin settings to a JSON file.
   *
   * @param settings - The settings object to export.
   * @returns A promise that resolves to true if the export was successful, false otherwise.
   */
  async exportSettings(settings) {
    try {
      if (!this.app) {
        throw new Error("App reference not set");
      }
      const settingsData = JSON.stringify(settings, null, 2);
      const electron = window.require ? window.require("electron") : null;
      const remote = electron ? electron.remote : null;
      if (!remote || !remote.dialog) {
        return this.exportToVault(settingsData);
      }
      const { canceled, filePath } = await remote.dialog.showSaveDialog({
        title: "Export AutoMover Settings",
        defaultPath: "AutoMover_settings.json",
        filters: [{ name: "JSON Files", extensions: ["json"] }],
        properties: ["createDirectory"]
      });
      if (canceled || !filePath) {
        return false;
      }
      const fs = require("node:fs");
      fs.writeFileSync(filePath, settingsData);
      LoggerUtil_default.infoNotice("Settings exported successfully");
      return true;
    } catch (error) {
      LoggerUtil_default.errorNotice("Failed to export settings", error);
      return false;
    }
  }
  /**
   * Exports the settings to the vault.
   * Exports the settings to a file named AutoMover_settings.json
   *
   * @param settingsData - The settings data to export.
   * @returns A promise that resolves to true if the export was successful, false otherwise.
   */
  async exportToVault(settingsData) {
    try {
      const filename = "AutoMover_settings.json";
      await this.app.vault.create(filename, settingsData);
      LoggerUtil_default.infoNotice(`Settings exported to vault: ${filename}`);
      return true;
    } catch (error) {
      LoggerUtil_default.errorNotice("Failed to export settings to vault", error);
      return false;
    }
  }
  /**
   * Imports settings from a JSON file.
   *
   * @returns The imported settings or null if the import failed.
   */
  async importSettings() {
    try {
      if (!this.app) {
        throw new Error("App reference not set");
      }
      const electron = window.require ? window.require("electron") : null;
      const remote = electron ? electron.remote : null;
      if (!remote || !remote.dialog) {
        return this.importFromVault();
      }
      const { canceled, filePaths } = await remote.dialog.showOpenDialog({
        title: "Import AutoMover Settings",
        filters: [{ name: "JSON Files", extensions: ["json"] }],
        properties: ["openFile"]
      });
      if (canceled || !filePaths || filePaths.length === 0) {
        return null;
      }
      const fs = require("node:fs");
      const fileContent = fs.readFileSync(filePaths[0], "utf8");
      const importedSettings = JSON.parse(fileContent);
      if (!this.validateSettings(importedSettings)) {
        LoggerUtil_default.warnNotice("Invalid settings file format");
        return null;
      }
      LoggerUtil_default.infoNotice("Settings imported successfully");
      return importedSettings;
    } catch (error) {
      LoggerUtil_default.errorNotice("Failed to import settings", error);
      return null;
    }
  }
  /**
   * Fallback method to import settings from the vault.
   * from the file AutoMover_settings.json
   *
   * @returns The imported settings or null if the import failed.
   */
  async importFromVault() {
    try {
      const filename = "AutoMover_settings.json";
      const file = this.app.vault.getAbstractFileByPath(filename);
      if (!file || !(file instanceof import_obsidian2.TFile)) {
        LoggerUtil_default.warnNotice(`Could not find ${filename} in vault`);
        return null;
      }
      const fileContent = await this.app.vault.read(file);
      const importedSettings = JSON.parse(fileContent);
      if (!this.validateSettings(importedSettings)) {
        LoggerUtil_default.warnNotice("Invalid settings file format");
        return null;
      }
      LoggerUtil_default.infoNotice("Settings imported from vault successfully");
      return importedSettings;
    } catch (error) {
      LoggerUtil_default.errorNotice("Failed to import settings from vault", error);
      return null;
    }
  }
  /**
   * Validates the settings object to ensure it has the correct structure.
   *
   * @param settings - The settings object to validate.
   * @return True if the settings object is valid, false otherwise.
   */
  validateSettings(settings) {
    if (!settings)
      return false;
    if (typeof settings.moveOnOpen !== "boolean")
      return false;
    if (!Array.isArray(settings.movingRules))
      return false;
    if (!Array.isArray(settings.exclusionRules))
      return false;
    if (typeof settings.automaticMoving !== "boolean")
      return false;
    if (settings.timer !== null && typeof settings.timer !== "number")
      return false;
    return true;
  }
};
var settingsIO = SettingsIO.getInstance();
var SettingsIO_default = settingsIO;

// Settings/Settings.ts
var DEFAULT_SETTINGS = {
  moveOnOpen: true,
  // moveOnSave: true,
  movingRules: [],
  exclusionRules: [],
  tagRules: [],
  projectRules: [],
  automaticMoving: false,
  timer: null,
  debugLogging: false,
  collapseSections: {
    tutorial: false,
    movingRules: false,
    exclusionRules: false,
    tagRules: false,
    projectRules: false
  }
};

// Utils/TimerUtil.ts
var TimerUtil = class {
  constructor() {
    this.timer = null;
  }
  static getInstance() {
    if (!TimerUtil.instance) {
      TimerUtil.instance = new TimerUtil();
    }
    return TimerUtil.instance;
  }
  formatTime(ms) {
    if (ms == null)
      return "00:00:00";
    const totalSeconds = Math.floor(ms / 1e3);
    const hours = String(Math.floor(totalSeconds / 3600)).padStart(2, "0");
    const minutes = String(Math.floor(totalSeconds % 3600 / 60)).padStart(
      2,
      "0"
    );
    const seconds = String(totalSeconds % 60).padStart(2, "0");
    return `${hours}:${minutes}:${seconds}`;
  }
  parseTimeToMs(timeStr) {
    const [h, m, s] = timeStr.split(":").map(Number);
    if ([h, m, s].some((n) => Number.isNaN(n)))
      return 0;
    return ((h != null ? h : 0) * 3600 + (m != null ? m : 0) * 60 + (s != null ? s : 0)) * 1e3;
  }
  startTimer(callback, interval) {
    if (this.timer) {
      clearInterval(this.timer);
    }
    this.timer = setTimeout(callback, interval);
  }
};
var timerUtil = TimerUtil.getInstance();
var TimerUtil_default = timerUtil;

// Settings/SettingsTab.ts
var import_obsidian3 = require("obsidian");

// Models/ExclusionRule.ts
var ExclusionRule = class {
  constructor(regex) {
    this.regex = regex || "";
  }
};

// Settings/ExclusionSection.ts
function exclusionSection(containerEl, plugin, display) {
  let saveTimeout = null;
  const debouncedSave = () => {
    if (saveTimeout)
      clearTimeout(saveTimeout);
    saveTimeout = setTimeout(() => {
      plugin.saveData(plugin.settings);
    }, 500);
  };
  const exclusionRuleContainer = containerEl.createDiv({
    cls: "moving_rules_container"
  });
  const exclusionRuleDetails = exclusionRuleContainer.createEl("details", {});
  exclusionRuleDetails.createEl("summary", { text: "Exclusion rules", cls: ["setting-item-heading"] });
  exclusionRuleDetails.open = !plugin.settings.collapseSections.exclusionRules;
  exclusionRuleDetails.addEventListener("toggle", async () => {
    plugin.settings.collapseSections.exclusionRules = !exclusionRuleDetails.open;
    await plugin.saveData(plugin.settings);
  });
  const exclusionList = exclusionRuleDetails.createDiv({
    cls: "rule_list"
  });
  const exclusionHeader = exclusionList.createDiv({
    cls: "rule margig_right"
  });
  exclusionHeader.createEl("p", {
    text: "Excluded folders or files (string or regex)",
    cls: "rule_title"
  });
  const addExclusionButton = exclusionHeader.createEl("button", {
    text: "+",
    cls: "rule_button"
  });
  addExclusionButton.addEventListener("click", () => {
    plugin.settings.exclusionRules.push(new ExclusionRule());
    display();
  });
  for (const exclusion of plugin.settings.exclusionRules) {
    const child = exclusionList.createDiv({ cls: "rule" });
    child.createEl("input", {
      value: exclusion.regex,
      cls: "rule_input"
    }).onchange = (e) => {
      exclusion.regex = e.target.value;
      debouncedSave();
    };
    const duplicateExclusionButton = child.createEl("button", {
      text: "\u2FFB",
      cls: "rule_button rule_button_duplicate"
    });
    duplicateExclusionButton.addEventListener("click", () => {
      plugin.settings.exclusionRules.push(new ExclusionRule(exclusion.regex));
      display();
    });
    const deleteExclusionButton = child.createEl("button", {
      text: "x",
      cls: "rule_button rule_button_remove"
    });
    deleteExclusionButton.addEventListener("click", () => {
      plugin.settings.exclusionRules = plugin.settings.exclusionRules.filter((r) => r !== exclusion);
      display();
    });
  }
}

// Models/MovingRule.ts
var MovingRule = class {
  constructor(regex, folder) {
    this.regex = regex || "";
    this.folder = folder || "";
  }
};

// Settings/MovingRuleSection.ts
function movingRuleSection(containerEl, plugin, display) {
  let saveTimeout = null;
  const debouncedSave = () => {
    if (saveTimeout)
      clearTimeout(saveTimeout);
    saveTimeout = setTimeout(() => {
      plugin.saveData(plugin.settings);
    }, 500);
  };
  const movingRulesContainer = containerEl.createDiv({
    cls: "moving_rules_container"
  });
  const movingRuleDetails = movingRulesContainer.createEl("details", {});
  movingRuleDetails.createEl("summary", { text: "Moving rules", cls: ["setting-item-heading"] });
  movingRuleDetails.open = !plugin.settings.collapseSections.movingRules;
  movingRuleDetails.addEventListener("toggle", async () => {
    plugin.settings.collapseSections.movingRules = !movingRuleDetails.open;
    await plugin.saveData(plugin.settings);
  });
  const ruleList = movingRuleDetails.createDiv({ cls: "rule_list" });
  const ruleHeader = ruleList.createDiv({ cls: "rule margig_right" });
  ruleHeader.createEl("p", {
    text: "Search criteria (string or regex)",
    cls: "rule_title"
  });
  ruleHeader.createEl("p", {
    text: "Folder (can contain regex groups)",
    cls: "rule_title"
  });
  const addRuleButton = ruleHeader.createEl("button", {
    text: "+",
    cls: "rule_button"
  });
  addRuleButton.addEventListener("click", () => {
    plugin.settings.movingRules.push(new MovingRule());
    display();
  });
  for (const rule of plugin.settings.movingRules) {
    const child = ruleList.createDiv({ cls: "rule" });
    child.createEl("input", {
      value: rule.regex,
      cls: "rule_input"
    }).onchange = (e) => {
      rule.regex = e.target.value;
      debouncedSave();
    };
    child.createEl("input", {
      value: rule.folder,
      cls: "rule_input"
    }).onchange = (e) => {
      rule.folder = e.target.value;
      debouncedSave();
    };
    const duplicateRuleButton = child.createEl("button", {
      text: "\u2FFB",
      cls: "rule_button rule_button_duplicate"
    });
    duplicateRuleButton.addEventListener("click", () => {
      plugin.settings.movingRules.push(new MovingRule(rule.regex, rule.folder));
      display();
    });
    const deleteRuleButton = child.createEl("button", {
      text: "x",
      cls: "rule_button rule_button_remove"
    });
    deleteRuleButton.addEventListener("click", () => {
      plugin.settings.movingRules = plugin.settings.movingRules.filter((r) => r !== rule);
      display();
    });
  }
}

// Settings/TagSection.ts
function tagSection(containerEl, plugin, display) {
  let saveTimeout = null;
  const debouncedSave = () => {
    if (saveTimeout)
      clearTimeout(saveTimeout);
    saveTimeout = setTimeout(() => {
      plugin.saveData(plugin.settings);
    }, 500);
  };
  const tagRuleContainer = containerEl.createDiv({
    cls: "moving_rules_container"
  });
  const tagRuleDetails = tagRuleContainer.createEl("details", {});
  tagRuleDetails.createEl("summary", { text: "Tag rules", cls: ["setting-item-heading"] });
  tagRuleDetails.open = !plugin.settings.collapseSections.tagRules;
  tagRuleDetails.addEventListener("toggle", async () => {
    plugin.settings.collapseSections.tagRules = !tagRuleDetails.open;
    await plugin.saveData(plugin.settings);
  });
  const tagList = tagRuleDetails.createDiv({
    cls: "rule_list"
  });
  const tagHeader = tagList.createDiv({
    cls: "rule margig_right"
  });
  tagHeader.createEl("p", {
    text: "Tag search criteria (string or regex)",
    cls: "rule_title"
  });
  const addTagButton = tagHeader.createEl("button", {
    text: "+",
    cls: "rule_button"
  });
  addTagButton.addEventListener("click", () => {
    plugin.settings.tagRules.push(new MovingRule());
    display();
  });
  for (const rule of plugin.settings.tagRules) {
    const child = tagList.createDiv({ cls: "rule" });
    child.createEl("input", {
      value: rule.regex,
      cls: "rule_input"
    }).onchange = (e) => {
      rule.regex = e.target.value;
      debouncedSave();
    };
    child.createEl("input", {
      value: rule.folder,
      cls: "rule_input"
    }).onchange = (e) => {
      rule.folder = e.target.value;
      debouncedSave();
    };
    const duplicateRuleButton = child.createEl("button", {
      text: "\u2FFB",
      cls: "rule_button rule_button_duplicate"
    });
    duplicateRuleButton.addEventListener("click", () => {
      plugin.settings.tagRules.push(new MovingRule(rule.regex, rule.folder));
      display();
    });
    const deleteRuleButton = child.createEl("button", {
      text: "x",
      cls: "rule_button rule_button_remove"
    });
    deleteRuleButton.addEventListener("click", () => {
      plugin.settings.tagRules = plugin.settings.tagRules.filter((r) => r !== rule);
      display();
    });
  }
}

// Models/ProjectRule.ts
var ProjectRule = class {
  constructor(projectName, folder, rules, collapsed) {
    this.projectName = projectName || "";
    this.folder = folder || "";
    this.rules = rules || [];
    this.collapsed = collapsed || false;
  }
};

// Settings/ProjectSection.ts
function projectSection(containerEl, plugin, display) {
  let saveTimeout = null;
  const debouncedSave = () => {
    if (saveTimeout)
      clearTimeout(saveTimeout);
    saveTimeout = setTimeout(() => {
      plugin.saveData(plugin.settings);
    }, 500);
  };
  const projectRuleContainer = containerEl.createDiv({
    cls: "moving_rules_container"
  });
  const projectRuleDetails = projectRuleContainer.createEl("details", {});
  projectRuleDetails.createEl("summary", { text: "Project rules", cls: ["setting-item-heading"] });
  projectRuleDetails.open = !plugin.settings.collapseSections.projectRules;
  projectRuleDetails.addEventListener("toggle", async () => {
    plugin.settings.collapseSections.projectRules = !projectRuleDetails.open;
    await plugin.saveData(plugin.settings);
  });
  const projectList = projectRuleDetails.createDiv({
    cls: "rule_list"
  });
  const projectHeader = projectList.createDiv({
    cls: "rule margig_right"
  });
  projectHeader.createEl("p", {
    text: "Project name",
    cls: "rule_title"
  });
  projectHeader.createEl("p", {
    text: "Destination",
    cls: "rule_title"
  });
  const addProjectButton = projectHeader.createEl("button", {
    text: "+",
    cls: "rule_button"
  });
  addProjectButton.addEventListener("click", () => {
    plugin.settings.projectRules.push(new ProjectRule());
    display();
  });
  for (const project of plugin.settings.projectRules) {
    const child = projectList.createDiv({ cls: "project" });
    const movingRulesDetails = child.createEl("details", {});
    const movingRulesSummary = movingRulesDetails.createEl("summary", {
      cls: ["setting-item-heading", "rule"]
    });
    movingRulesDetails.open = !project.collapsed;
    movingRulesDetails.addEventListener("toggle", async () => {
      project.collapsed = !movingRulesDetails.open;
      await plugin.saveData(plugin.settings);
    });
    movingRulesSummary.createEl("input", {
      value: project.projectName,
      cls: "rule_input"
    }).onchange = (e) => {
      project.projectName = e.target.value;
      debouncedSave();
    };
    movingRulesSummary.createEl("input", {
      value: project.folder,
      cls: "rule_input"
    }).onchange = (e) => {
      project.folder = e.target.value;
      debouncedSave();
    };
    const addRuleButton = movingRulesSummary.createEl("button", {
      text: "+",
      cls: "rule_button"
    });
    addRuleButton.addEventListener("click", () => {
      project.rules.push(new MovingRule());
      display();
    });
    const duplicateRuleButton = movingRulesSummary.createEl("button", {
      text: "\u2FFB",
      cls: "rule_button rule_button_duplicate"
    });
    duplicateRuleButton.addEventListener("click", () => {
      plugin.settings.projectRules.push(new ProjectRule(project.projectName, project.folder));
      display();
    });
    const deleteRuleButton = movingRulesSummary.createEl("button", {
      text: "x",
      cls: "rule_button rule_button_remove"
    });
    deleteRuleButton.addEventListener("click", () => {
      plugin.settings.projectRules = plugin.settings.projectRules.filter((p) => p !== project);
      display();
    });
    const movingRules = movingRulesDetails.createDiv();
    for (const rule of project.rules) {
      const child2 = movingRules.createDiv({ cls: "project_rule" });
      child2.createEl("input", {
        value: rule.regex,
        cls: "rule_input"
      }).onchange = (e) => {
        rule.regex = e.target.value;
        debouncedSave();
      };
      child2.createEl("input", {
        value: rule.folder,
        cls: "rule_input"
      }).onchange = (e) => {
        rule.folder = e.target.value;
        debouncedSave();
      };
      const duplicateRuleButton2 = child2.createEl("button", {
        text: "\u2FFB",
        cls: "rule_button rule_button_duplicate"
      });
      duplicateRuleButton2.addEventListener("click", () => {
        project.rules.push(new MovingRule(rule.regex, rule.folder));
        display();
      });
      const deleteRuleButton2 = child2.createEl("button", {
        text: "x",
        cls: "rule_button rule_button_remove"
      });
      deleteRuleButton2.addEventListener("click", () => {
        project.rules = project.rules.filter((r) => r !== rule);
        display();
      });
    }
  }
}

// Settings/SettingsTab.ts
var SettingsTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.display = () => {
      const { containerEl } = this;
      containerEl.empty();
      new import_obsidian3.Setting(containerEl).setName("Automatic moving").setHeading();
      new import_obsidian3.Setting(containerEl).setName("Export/Import of settings").setDesc(
        `Import will replace the current settings.
         If you aren't prompted to choose a location, then the file will be exported to/imported from the vault root as AutoMover_settings.json (json files aren't visible in the vault by default).`
      ).addButton((button) => {
        button.setButtonText("Export settings");
        button.onClick(async () => {
          SettingsIO_default.exportSettings(this.plugin.settings);
        });
      }).addButton((button) => {
        button.setButtonText("Import settings");
        button.onClick(async () => {
          const importedSettings = await SettingsIO_default.importSettings();
          if (importedSettings) {
            this.plugin.settings = importedSettings;
            await this.plugin.saveData(this.plugin.settings);
            this.plugin.app.workspace.trigger("AutoMover:automatic-moving-update", this.plugin.settings);
            this.display();
          }
        });
      });
      new import_obsidian3.Setting(containerEl).setName("Move on open").setDesc("Should the file be moved when it is opened?").addToggle(
        (cb) => cb.setValue(this.plugin.settings.moveOnOpen).onChange(async (value) => {
          this.plugin.settings.moveOnOpen = value;
          await this.plugin.saveData(this.plugin.settings);
        })
      );
      new import_obsidian3.Setting(containerEl).setName("Manually move").setDesc("Execute the command to go through your notes and move them according to the rules specified below.").addButton((button) => {
        button.setButtonText("Move files");
        button.onClick(async () => {
          this.plugin.goThroughAllFiles();
        });
      });
      const automaticMovingContainer = containerEl.createDiv({});
      new import_obsidian3.Setting(automaticMovingContainer).setName("Automatic moving").setDesc(
        `Execute a timed event that goes through all the files and moves them according to the rules specified below.
		 The formatting is hh:mm:ss (if set 00:05:00 it will execute every 5 minutes).
	     If the timer is set to 0, the automatic moving will do nothing.`
      ).setClass("timer-setting").addToggle(
        (cb) => cb.setValue(this.plugin.settings.automaticMoving).onChange(async (value) => {
          this.plugin.settings.automaticMoving = value;
          await this.plugin.saveData(this.plugin.settings);
          this.app.workspace.trigger("AutoMover:automatic-moving-update", this.plugin.settings);
          this.display();
        })
      ).addText(
        (cb) => cb.setDisabled(!this.plugin.settings.automaticMoving).setValue(TimerUtil_default.formatTime(this.plugin.settings.timer)).setPlaceholder("hh:mm:ss").onChange(async (value) => {
          this.plugin.settings.timer = TimerUtil_default.parseTimeToMs(value);
          await this.plugin.saveData(this.plugin.settings);
          this.app.workspace.trigger("AutoMover:automatic-moving-update", this.plugin.settings);
        })
      );
      new import_obsidian3.Setting(containerEl).setName("Debug logging").setDesc(
        "Log verbose debug messages to the developer console (Ctrl+Shift+I). Leave off unless diagnosing an issue."
      ).addToggle(
        (cb) => cb.setValue(this.plugin.settings.debugLogging).onChange(async (value) => {
          this.plugin.settings.debugLogging = value;
          await this.plugin.saveData(this.plugin.settings);
        })
      );
      const tutorialContainer = containerEl.createDiv({
        cls: "moving_rules_container"
      });
      const tutorialDetails = tutorialContainer.createEl("details", {});
      tutorialDetails.createEl("summary", { text: "Tutorial", cls: ["setting-item-heading"] });
      tutorialDetails.open = !this.plugin.settings.collapseSections.tutorial;
      tutorialDetails.addEventListener("toggle", async () => {
        this.plugin.settings.collapseSections.tutorial = !tutorialDetails.open;
        await this.plugin.saveData(this.plugin.settings);
      });
      const tutorialDetailsContainer = tutorialDetails.createDiv({});
      const description = tutorialDetailsContainer.createDiv();
      description.createSpan({
        text: "This plugin allows you to move files to a specified folder based on the file name."
      });
      description.createEl("br", {});
      description.createSpan({
        text: "If you have multiple rules referencing the same file, the first rule will be applied."
      });
      description.createEl("br", {});
      description.createSpan({
        text: "Usage of regex groups is supported. To use them in the folder name, use $1, $2, etc. to reference the group."
      });
      description.createEl("br", {});
      description.createEl("br", {});
      description.createSpan({ text: "Examples: ", cls: "rule_title" });
      description.createEl("br", {});
      description.createSpan({
        text: "To move files containing 'Scroll' to a folder named 'Scrolls': "
      });
      const example1 = description.createDiv({ cls: "rule margig_right" });
      example1.createSpan({ text: "Scroll", cls: "rule_title" });
      example1.createSpan({ text: "Scrolls", cls: "rule_title" });
      description.createSpan({
        text: "To move files containing the word 'Scroll' and a number to space -> to a folder named 'Scrolls' under the subfolder of the scroll number: "
      });
      const example2 = description.createDiv({ cls: "rule margig_right" });
      example2.createSpan({ text: "Scroll (\\d+)", cls: "rule_title" });
      example2.createSpan({ text: "Scrolls/$1", cls: "rule_title" });
      movingRuleSection(containerEl, this.plugin, this.display);
      tagSection(containerEl, this.plugin, this.display);
      exclusionSection(containerEl, this.plugin, this.display);
      projectSection(containerEl, this.plugin, this.display);
    };
    this.plugin = plugin;
  }
};

// Utils/ExclusionMatcherUtil.ts
var ExclusionMatcherUtil = class {
  constructor() {
    this.regexCache = /* @__PURE__ */ new Map();
  }
  static getInstance() {
    if (!ExclusionMatcherUtil.instance) {
      ExclusionMatcherUtil.instance = new ExclusionMatcherUtil();
    }
    return ExclusionMatcherUtil.instance;
  }
  /**
   * Gets a compiled regex from cache or creates and caches it
   * @param pattern - The regex pattern string
   * @returns RegExp
   */
  getCompiledRegex(pattern) {
    if (!this.regexCache.has(pattern)) {
      this.regexCache.set(pattern, new RegExp(pattern));
    }
    return this.regexCache.get(pattern);
  }
  /**
   * This method is used to check if the file is excluded by the exclusion rule
   * @param file - The file to be checked
   * @param exclusionRules - The exclusion rule to be used
   * @returns true if the file path is excluded, false otherwise
   */
  isFilePathExcluded(file, exclusionRules) {
    for (const rule of exclusionRules) {
      const regex = this.getCompiledRegex(rule.regex);
      if (regex.test(file.path)) {
        return true;
      }
    }
    return false;
  }
};
var exclusionMatcherUtil = ExclusionMatcherUtil.getInstance();
var ExclusionMatcherUtil_default = exclusionMatcherUtil;

// Utils/MovingUtil.ts
var import_obsidian4 = require("obsidian");
var MovingUtil = class {
  constructor() {
  }
  static getInstance() {
    if (!MovingUtil.instance) {
      MovingUtil.instance = new MovingUtil();
    }
    return MovingUtil.instance;
  }
  init(app) {
    this.app = app;
  }
  /**
   * Checks if the path is a file
   *
   * @param path - Path to be checked
   * @returns boolean
   */
  isFile(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    return file instanceof import_obsidian4.TFile;
  }
  /**
   * Checks if the path is a folder
   *
   * @param path - Path to be checked
   * @returns boolean
   */
  isFolder(path) {
    return this.app.vault.getAbstractFileByPath(path) instanceof import_obsidian4.TFolder;
  }
  /**
   * Moves a file into the destination folder, preserving its name.
   *
   * Behavior:
   * - If the file is already at the destination, returns `"no_op"` without touching the vault.
   * - If another file already occupies the destination path, returns `"duplicate"`
   *   (checked up-front via `getAbstractFileByPath` rather than by parsing rename errors).
   * - If the destination folder doesn't exist, intermediate folders are created; failure
   *   to create them returns `"invalid_path"`.
   * - Any other rename rejection is caught, logged, and returned as `"error"`.
   *
   * @param file - File to be moved
   * @param newPath - Destination folder (the file's own name is appended automatically)
   * @returns a {@link MoveOutcome} describing what happened
   */
  async moveFile(file, newPath) {
    const targetPath = `${newPath}/${file.name}`;
    if (file.path === targetPath) {
      return "no_op";
    }
    if (this.app.vault.getAbstractFileByPath(targetPath)) {
      LoggerUtil_default.debug(`Duplicate at "${targetPath}", skipping "${file.path}"`);
      return "duplicate";
    }
    if (!this.isFolder(newPath)) {
      const created = await this.createMissingFolders(newPath);
      if (!created) {
        LoggerUtil_default.error(`Could not create destination folder "${newPath}"`);
        return "invalid_path";
      }
    }
    try {
      await this.app.vault.rename(file, targetPath);
      return "moved";
    } catch (e) {
      LoggerUtil_default.error(`Failed to move "${file.path}" -> "${targetPath}": ${e}`);
      return "error";
    }
  }
  /**
   * Moves the folder to the destination path
   *
   * @param folder - Folder to be moved
   * @param newPath - Destination path
   * @returns void
   */
  moveFolder(folder, newPath) {
    if (this.isFolder(newPath)) {
      this.app.vault.rename(folder, `${newPath}/${folder.name}`);
    } else {
      LoggerUtil_default.errorNotice(`Invalid destination path
${newPath} is not a folder!`);
    }
  }
  /**
   * Creates folder in destination path if it does not exist already
   *
   * @param path - Path of the folder to be created
   * @returns Created folder or null if folder already exists
   */
  createFolder(path) {
    if (!this.isFolder(path)) {
      this.app.vault.createFolder(path).then((folder) => {
        return folder;
      });
    } else {
      LoggerUtil_default.errorNotice("Folder already exists");
    }
    return null;
  }
  /**
   * Splits the path into an array of strings
   *
   * @param path - Path to be split
   * @returns string[]
   */
  splitPath(path) {
    return path.split("/");
  }
  /**
   * Create missing folders in the path
   *
   * @param path - Path to be checked
   * @returns void
   */
  async createMissingFolders(path) {
    const splitPath = this.splitPath(path);
    let currentPath = "";
    for (const folder of splitPath) {
      currentPath += folder;
      if (!this.isFolder(currentPath)) {
        await this.app.vault.createFolder(path);
      }
      currentPath += "/";
    }
    if (this.isFolder(path)) {
      return true;
    }
    return false;
  }
};
var movingUtil = MovingUtil.getInstance();
var MovingUtil_default = movingUtil;

// Utils/RuleMatcherUtil.ts
var RuleMatcherUtil = class {
  constructor() {
    this.regexCache = /* @__PURE__ */ new Map();
  }
  /**
   * Returns the singleton instance of RuleMatcherUtil, creating it on first access.
   *
   * @returns RuleMatcherUtil
   */
  static getInstance() {
    if (!RuleMatcherUtil.instance) {
      RuleMatcherUtil.instance = new RuleMatcherUtil();
    }
    return RuleMatcherUtil.instance;
  }
  /**
   * Gets a compiled regex from cache or creates and caches it
   * @param pattern - The regex pattern string
   * @returns RegExp
   */
  getCompiledRegex(pattern) {
    if (!this.regexCache.has(pattern)) {
      this.regexCache.set(pattern, new RegExp(pattern));
    }
    return this.regexCache.get(pattern);
  }
  /**
   * Returns the first rule that matches the file
   * If no rule matches, returns null
   *
   * @param file
   * @param rules
   * @returns MovingRule | null
   */
  getMatchingRuleByName(file, rules) {
    for (const rule of rules) {
      if (rule.regex == null || rule.regex === "") {
        LoggerUtil_default.error("Rule does not have a regex: ", rule);
        continue;
      }
      if (rule.folder == null || rule.folder === "") {
        LoggerUtil_default.error("Rule does not have a destination folder: ", rule);
        continue;
      }
      if (!this.isValidRegex(rule.regex)) {
        LoggerUtil_default.error("Rule has an invalid regex: ", rule);
        continue;
      }
      const regex = this.getCompiledRegex(rule.regex);
      if (regex.test(file.name)) {
        return rule;
      }
    }
    return null;
  }
  /**
   * Returns the first rule that matches any of the tags
   * If no rule matches, returns null
   * @param tags
   * @param rules
   * @returns MovingRule | null
   */
  getMatchingRuleByTag(tags, rules) {
    for (const rule of rules) {
      if (rule.regex == null || rule.regex === "") {
        LoggerUtil_default.error("Tag Rule does not have a regex: ", rule);
        continue;
      }
      if (rule.folder == null || rule.folder === "") {
        LoggerUtil_default.error("Tag Rule does not have a destination folder: ", rule);
        continue;
      }
      if (!this.isValidRegex(rule.regex)) {
        LoggerUtil_default.error("Tag Rule has an invalid regex: ", rule);
        continue;
      }
      const regex = this.getCompiledRegex(rule.regex);
      for (const tag of tags) {
        if (regex.test(tag)) {
          return rule;
        }
      }
    }
    return null;
  }
  /**
   * Returns the regex groups of the file that match the rule
   * If no groups match, returns an empty array
   *
   * @param file
   * @param rule
   * @returns string[]
   */
  getGroupMatches(file, rule) {
    const regex = this.getCompiledRegex(rule.regex);
    const matches = file.name.match(regex);
    return matches;
  }
  /**
   * Returns the regex groups from the first tag that matches the rule
   * If no tag matches, returns null
   *
   * @param tags - The list of tags to test
   * @param rule - The rule whose regex is applied to each tag
   * @returns RegExpMatchArray | null
   */
  getGroupMatchesForTags(tags, rule) {
    const regex = this.getCompiledRegex(rule.regex);
    for (const tag of tags) {
      const matches = tag.match(regex);
      if (matches) {
        return matches;
      }
    }
    return null;
  }
  /**
   * Checks if the regex pattern is valid
   * Meaning, syntax errors are caught, but not logical errors
   *
   * @param pattern
   * @returns boolean
   */
  isValidRegex(pattern) {
    try {
      new RegExp(pattern);
      return true;
    } catch (e) {
      if (e instanceof SyntaxError) {
        LoggerUtil_default.error(`Invalid regex pattern: ${e.message}`);
      }
      return false;
    }
  }
  /**
   * Constructs the final destination path from the matched groups
   * The path is constructed by replacing the $1, $2, $3, etc. with the matched groups
   *
   * @param rule
   * @param matches
   */
  constructFinalDesinationPath(rule, matches) {
    var _a;
    let folderPath = rule.folder;
    const unnamedGroups = this.getUnnamedGroups(rule.regex);
    for (let i = 0; i < unnamedGroups.length; i++) {
      folderPath = folderPath.replace(`$${i + 1}`, (_a = matches[i + 1]) != null ? _a : "");
    }
    return folderPath;
  }
  /**
   * Is regex grouped
   * Groups are defined by (...) and used with $1, $2, $3, etc.
   *
   * @param rule
   * @returns boolean
   */
  isRegexGrouped(rule) {
    return this.doesDestinationUseGroups(rule) && this.getUnnamedGroups(rule.regex) != null;
  }
  /**
   * Returns the unnamed groups in the regex pattern
   *
   * @param pattern
   * @returns RegExpMatchArray | null
   */
  getUnnamedGroups(pattern) {
    return pattern.match(/\(/g);
  }
  /**
   * Does destination use groups
   * Groups are defined by $1, $2, $3, etc.
   *
   * @param rule
   * @returns boolean
   */
  doesDestinationUseGroups(rule) {
    return /\$\d/.test(rule.folder);
  }
};
var ruleMatcherUtil = RuleMatcherUtil.getInstance();
var RuleMatcherUtil_default = ruleMatcherUtil;

// main.ts
var obsidian = __toESM(require("obsidian"));

// Utils/ProjectMatcherUtil.ts
var ProjectMatcherUtil = class {
  constructor() {
  }
  static getInstance() {
    if (!ProjectMatcherUtil.instance) {
      ProjectMatcherUtil.instance = new ProjectMatcherUtil();
    }
    return ProjectMatcherUtil.instance;
  }
  /**
   * Returns the first project rule that matches the file
   * If no rule matches, returns null
   * @param projectName
   * @param projectRules
   * @returns ProjectRule | null
   */
  getMatchingProjectRule(projectName, projectRules) {
    for (const projectRule of projectRules) {
      if (projectRule.projectName === projectName) {
        return projectRule;
      }
    }
    return null;
  }
  /**
   * Prepends the project folder to the destination path
   * and checks whether the project folder ends with a slash
   *
   * @param projectRule
   * @param subPath
   * @returns string
   */
  constructProjectDestinationPath(projectRule, subPath) {
    let projectFolder = projectRule.folder;
    if (!projectFolder.endsWith("/")) {
      projectFolder += "/";
    }
    return projectFolder + subPath;
  }
};
var projectMatcherUtil = ProjectMatcherUtil.getInstance();
var ProjectMatcherUtil_default = projectMatcherUtil;

// main.ts
var AutoMoverPlugin = class extends obsidian.Plugin {
  /**
   * Obsidian lifecycle hook called when the plugin is enabled.
   * Initializes utilities, loads settings, registers the settings tab,
   * file-open and automatic-moving events, the command, and the ribbon icon.
   *
   * @returns void
   */
  async onload() {
    MovingUtil_default.init(this.app);
    SettingsIO_default.init(this.app);
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    LoggerUtil_default.init(this);
    this.addSettingTab(new SettingsTab(this.app, this));
    this.automaticMoving();
    if (!this.areMovingTriggersEnabled())
      return;
    if (!this.areThereRulesToApply())
      return;
    this.registerEvent(
      this.app.workspace.on("file-open", async (file) => {
        if (!this.settings.moveOnOpen)
          return;
        if (file == null || file.path == null)
          return;
        if (this.isFileExcluded(file))
          return;
        const result = await this.matchAndMoveFile(file);
        if (result === "moved")
          LoggerUtil_default.infoNotice("1 file moved.");
        else if (result === "duplicate")
          LoggerUtil_default.infoNotice("1 file not moved - duplicate name.");
        else if (result === "invalid_path" || result === "error")
          LoggerUtil_default.infoNotice("1 file failed to move.");
      })
    );
    this.registerEvent(
      // since i am defining my own event, ts-lint is crying about it but it works in the end
      this.app.workspace.on("AutoMover:automatic-moving-update", () => {
        LoggerUtil_default.debug("Automatic moving update");
        this.automaticMoving();
      })
    );
    this.addCommand({
      id: "AutoMover:move-files",
      name: "Move files",
      callback: () => {
        this.goThroughAllFiles();
      }
    });
    this.addRibbonIcon("file-input", "AutoMover: Move files", () => {
      this.goThroughAllFiles();
    });
  }
  /**
   * Reocurring function that will be called by the timer
   *
   * @returns void
   */
  automaticMoving() {
    if (!this.settings.automaticMoving)
      return;
    if (this.settings.timer == null || this.settings.timer <= 0)
      return;
    this.goThroughAllFiles({ silentIfUnchanged: true });
    TimerUtil_default.startTimer(this.automaticMoving.bind(this), this.settings.timer);
  }
  /**
   * Opens all files in the repository so that the even "file-open" is triggered
   *
   * @returns void
   */
  async goThroughAllFiles(options = {}) {
    const candidates = [];
    for (const file of this.app.vault.getFiles()) {
      if (file == null || file.path == null)
        continue;
      if (this.isFileExcluded(file))
        continue;
      candidates.push(file);
    }
    const results = await Promise.all(candidates.map((file) => this.matchAndMoveFile(file)));
    let moved = 0;
    let duplicate = 0;
    let failed = 0;
    for (const result of results) {
      if (result === "moved")
        moved++;
      else if (result === "duplicate")
        duplicate++;
      else if (result === "invalid_path" || result === "error")
        failed++;
    }
    if (options.silentIfUnchanged && moved === 0)
      return;
    const lines = [];
    if (moved > 0)
      lines.push(`${moved} ${moved === 1 ? "file" : "files"} moved.`);
    if (duplicate > 0)
      lines.push(`${duplicate} ${duplicate === 1 ? "file" : "files"} not moved - duplicate name.`);
    if (failed > 0)
      lines.push(`${failed} ${failed === 1 ? "file" : "files"} failed to move.`);
    LoggerUtil_default.infoNotice(lines.length === 0 ? "No files needed to be moved." : lines.join("\n"));
  }
  /**
   * Checks if the file is excluded by the exclusion rule
   *
   * @param file - The file to be checked
   * @returns true if the file path is excluded, false otherwise
   */
  isFileExcluded(file) {
    if (!this.areThereExcludedFolders())
      return false;
    if (!this.areThereRulesToApply())
      return false;
    return ExclusionMatcherUtil_default.isFilePathExcluded(file, this.settings.exclusionRules);
  }
  /**
   * Matches the file to the first applicable rule (project, then name, then tag)
   * and moves it.
   *
   * @param file - File to be matched and moved
   * @returns the MoveOutcome from the matched rule, or null if no rule matched
   */
  async matchAndMoveFile(file) {
    const projectResult = await this.matchAndMoveByProject(file);
    if (projectResult !== null)
      return projectResult;
    const nameResult = await this.matchAndMoveByName(file);
    if (nameResult !== null)
      return nameResult;
    return this.matchAndMoveByTag(file);
  }
  /**
   * Matches the file by name and moves it to the destination folder.
   *
   * @param file - File to be matched and moved
   * @returns the MoveOutcome, or null if no rule matched
   */
  async matchAndMoveByName(file) {
    const rule = RuleMatcherUtil_default.getMatchingRuleByName(file, this.settings.movingRules);
    if (rule == null || rule.folder == null)
      return null;
    if (RuleMatcherUtil_default.isRegexGrouped(rule)) {
      const matches = RuleMatcherUtil_default.getGroupMatches(file, rule);
      const finalDestinationPath = RuleMatcherUtil_default.constructFinalDesinationPath(rule, matches);
      return MovingUtil_default.moveFile(file, finalDestinationPath);
    }
    return MovingUtil_default.moveFile(file, rule.folder);
  }
  /**
   * Matches the file by tags it contains and moves it to the destination folder.
   *
   * @param file - File to be matched and moved
   * @returns the MoveOutcome, or null if no rule matched
   */
  async matchAndMoveByTag(file) {
    const cache = this.app.metadataCache.getFileCache(file);
    if (cache == null)
      return null;
    const tags = obsidian.getAllTags(cache);
    if (tags == null || tags.length === 0)
      return null;
    const tagRule = RuleMatcherUtil_default.getMatchingRuleByTag(tags, this.settings.tagRules);
    if (tagRule == null || tagRule.folder == null)
      return null;
    if (RuleMatcherUtil_default.isRegexGrouped(tagRule)) {
      const matches = RuleMatcherUtil_default.getGroupMatchesForTags(tags, tagRule);
      const finalDestinationPath = RuleMatcherUtil_default.constructFinalDesinationPath(tagRule, matches);
      return MovingUtil_default.moveFile(file, finalDestinationPath);
    }
    return MovingUtil_default.moveFile(file, tagRule.folder);
  }
  /**
   * Matches the file by its `Project` (or `project`) frontmatter value and
   * moves it according to the matched project rule. If the project rule has
   * inner rules, the first matching inner rule's destination is appended;
   * otherwise (or on a "./" destination) the file is moved to the project root.
   *
   * @param file - File to be matched and moved
   * @returns the MoveOutcome, or null if no project rule matched
   */
  async matchAndMoveByProject(file) {
    const cache = this.app.metadataCache.getFileCache(file);
    if (cache == null)
      return null;
    if (cache.frontmatter == null)
      return null;
    if (cache.frontmatter.Project == null && cache.frontmatter.project == null)
      return null;
    const projectName = cache.frontmatter.Project || cache.frontmatter.project;
    const projectRule = ProjectMatcherUtil_default.getMatchingProjectRule(projectName, this.settings.projectRules);
    if (projectRule == null || projectRule.folder == null)
      return null;
    if (projectRule.rules == null || projectRule.rules.length === 0) {
      LoggerUtil_default.debug("No rules defined, moving to project root");
      return MovingUtil_default.moveFile(file, projectRule.folder);
    }
    const rule = RuleMatcherUtil_default.getMatchingRuleByName(file, projectRule.rules);
    if (rule == null || rule.folder === "./") {
      LoggerUtil_default.debug("No matching rule or './' destination, moving to project root");
      return MovingUtil_default.moveFile(file, projectRule.folder);
    }
    if (RuleMatcherUtil_default.isRegexGrouped(rule)) {
      const matches = RuleMatcherUtil_default.getGroupMatches(file, rule);
      const ruleDesinationPath = RuleMatcherUtil_default.constructFinalDesinationPath(rule, matches);
      const finalDestinationPath2 = ProjectMatcherUtil_default.constructProjectDestinationPath(projectRule, ruleDesinationPath);
      return MovingUtil_default.moveFile(file, finalDestinationPath2);
    }
    const finalDestinationPath = ProjectMatcherUtil_default.constructProjectDestinationPath(projectRule, rule.folder);
    return MovingUtil_default.moveFile(file, finalDestinationPath);
  }
  /**
   * Reloads the plugin settings from disk, merged on top of DEFAULT_SETTINGS.
   *
   * @returns void
   */
  async asyncloadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  /**
   * Obsidian lifecycle hook called when the plugin is disabled or reloaded.
   *
   * @returns void
   */
  async onunload() {
  }
  /**
   * No point in doing anything if there is no trigger set which will cause you to move the files
   * @returns boolean
   */
  areMovingTriggersEnabled() {
    return this.settings.moveOnOpen;
  }
  /**
   * If there are no rules to apply, then there is no point in checking for them
   * @returns boolean
   */
  areThereRulesToApply() {
    return this.settings.movingRules.length > 0 && this.settings.movingRules.some((rule) => rule.regex !== "" && rule.folder !== "") || this.settings.tagRules.length > 0 && this.settings.tagRules.some((rule) => rule.regex !== "" && rule.folder !== "") || this.areThereProjectRulesToApply();
  }
  /**
   * If there are no project rules to apply, then there is no point in checking for them
   * @returns boolean
   */
  areThereProjectRulesToApply() {
    return this.settings.projectRules.length > 0 && this.settings.projectRules.some((projectRule) => projectRule.projectName !== "" && projectRule.folder !== "");
  }
  /**
   * If there are no excluded folders, then we can move thing freely
   * @returns boolean
   */
  areThereExcludedFolders() {
    return this.settings.exclusionRules.length > 0;
  }
  /**
   * Superficail check if the rules are valid
   * @returns boolean
   */
  areRulesValid() {
    return this.settings.movingRules.every((rule) => rule.regex !== "" && rule.folder !== "") && this.settings.tagRules.every((rule) => rule.regex !== "" && rule.folder !== "");
  }
  /**
   * Superficail check if the excluded folders are valid
   * @returns boolean
   */
  areExcludedFoldersValid() {
    return this.settings.exclusionRules.every((rule) => rule.regex !== "");
  }
};


/* nosourcemap */